alias _G='cd "$DINGLEHOPPER/_GLOBAL"';
alias _M='cd "$HOME/_M"';
alias -s gp5=abc
alias -s pbcopy="pbcopy"
alias -s gpx=abc
alias -s gtk="gittaku $@"
alias -s js="node $@"
alias -s json="jq $@"
alias -s md="info $@"
alias -s ptb=abc
alias -s taku=cat
alias 3.='cd ../../../'
alias .......='cd ../../../../../..'
alias ......='cd ../../../../..'
alias .....='cd ../../../..'
alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
alias 0bsd="license"
alias acp="git add-commit-push --no-verify"
alias backend='cd "$SRC/dinglehopper/src/backend"'
alias be='cd "$SRC/dinglehopper/src/backend"'
alias bend='cd "$SRC/dinglehopper/src/backend"'
alias bin='cd "$BIN"'
alias bk="back_up"
alias bkgd='afplay "$BKGD" &'
alias bkup="back_up"
alias bp='cd "$BLUEPRINTS"';
alias btldr="doom /Users/donaldmoore/.config/_____CONFIG.JSON_HOOMAN_BOOTLOADER"
alias btstrpr="cd $DINGLEHOPPER/modules/bootstrapper"
alias c="pbcopy"
alias cache='cd "$XDG_CACHE_HOME"'
# alias cash="$money"
alias cdspc='codespace'
alias ce="emacs \"$(which $1)\"" # command edit
alias cedit="emacs \"$(which $1)\"" # command edit
alias cf="cloudflared"
alias clean-precmd="precmd_functions=()"
alias cli='cd "$SRC/dinglehopper/src/cli"'
alias cloudflare="cloudflared"
alias cnt='cd "$HOME/src"'
alias copycat="copy"
alias d="print -rl -- ./*(DR/)"
alias data='cd "$XDG_DATA_HOME"'
alias df='df -h'
alias dirs="print -rl -- ./*(DR/)"
alias docs="cd $DOCS"
alias dw="$DOWNLOADS"
alias dwm="/opt/homebrew/bin/dwm";
alias dwn="$DOWNLOADS"
alias env='env | sort' # Sorted environment variables
alias eq="cd /Users/donaldmoore/Documents/Aequilibrium"
alias f="print -rl -- ./*(DR.)"
alias fe='emacs' # file edit
alias fedit='emacs' # file edit
alias fend='cd "$SRC/dinglehopper/src/frontend"'
alias files="print -rl -- ./*(DR.)"
alias free='vm_stat' # Memory usage details on macOS
alias frontend='cd "$SRC/dinglehopper/src/frontend"'
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff'
alias git-branch="git branch -v"
alias git-remote="git remote -v"
alias gl='git pull'
alias gp='git push'
alias gs='git status'
alias h='history'
alias hexedit="hexedit --color $@"
alias history='fc -l 1' # Full history
alias homebrew="brew"
alias i=$ICLOUD_DRIVE
alias icloud=$ICLOUD_DRIVE
alias imgnxlog=" 70960C40-F14F-49E5-ABE6-EACEAE25F79B $@"
alias iphonefix="noiphone"
alias jsh='ish || cd "$JSH"'
alias l.="eza './.??*'" # l. (you might see a bullet point because of a common ligature)
alias l="eza"
alias l="print -rl -- ./*(DR@)"
alias la='eza --long --all -bGF --header --git --color=always --group-directories-first --icons'
alias labs='cd "$LABS"'
alias launch="cd $HOME/Library/LaunchAgents/"
alias launchagents="cd $HOME/Library/LaunchAgents/"
alias ld='eza -1 --color=always --group-directories-first --icons'
alias lear="clear"
alias lh="eza -a | grep -E '^\.|^total'"
alias lib='cd "$LIB"'
alias links="print -rl -- ./*(DR@)"
alias lisp="sbcl"
alias list-hooks="echo 'All hooks:'; echo 'precmd:' \"\${precmd_functions[@]}\"; echo 'preexec:' \"\${preexec_functions[@]}\"; echo 'periodic:' \"\${periodic_functions[@]}\""
alias list-precmd="echo 'precmd_functions:'; printf '%s\n' \"\${precmd_functions[@]}\""
alias ll='eza -la --octal-permissions --group-directories-first'
alias llm='eza -lbGd --header --git --sort=modified --color=always --group-directories-first'
alias localhost="cd $DINGLEHOPPER/srv && ./serve.local"
alias ls='eza'
alias lsa='ls -lahO' # long, all, human-readable, and output flags (macOS)
alias lsd.="eza -d -a | grep -E '^\.'"
alias lsdh.="eza -d -a | grep -E '^\.'"
alias lsdh="eza -d | grep -E '^\.'"
alias lsrv="cd $DINGLEHOPPER/srv && ./serve.local"
alias lx='eza -lbhHigUmuSa@ --time-style=long-iso --git --color-scale --color=always --group-directories-first'
alias m='"$MEDIA"'
alias MAGICEYE="/Users/donaldmoore/src/dinglehopper/utils/magic-eye"
alias midi="cd /Users/donaldmoore/src/dinglehopper/triage/digital-audio-workspace/components/midi/navigators-wheel-circle-of-fifths-instrument.d/"
alias mkdir='mkdir -p'
alias money='"$HOME/Library/Mobile Documents/com~apple~CloudDocs/_____WORKBENCH/src/utils/financial/calculator"'
alias mount='mount | column -t' # Formatted mount points
alias mx="code -r $XDG_CONFIG_HOME/hammerspoon/init.lua"
alias netstat='netstat -tuln' # Network connections with details
alias p="python3"
alias pb="pbcopy || pbpaste"
alias pcnf="doom /Users/donaldmoore/.config/_____CONFIG.JSON_HOOMAN_BOOTLOADER"
alias pi="ssh pi@zero2w.local"
alias pins=". ./.venv/bin/activate"
alias pip="python -m pip"
alias plist="cd $HOME/Library/LaunchAgents/"
alias ql="sbcl --load /Users/donaldmoore/lib/quicklisp/quicklisp.lisp"
alias qls="sbcl --load /Users/donaldmoore/quicklisp/setup.lisp"
alias r="\033[0m"
alias rd="print -rl -- ./**/*(D/)"
alias re="reset"
alias recursive_dirs="print -rl -- ./**/*(D/)"
alias recursive_files="print -rl -- ./**/*(D.)"
alias recursive_links="print -rl -- ./**/*(@D)"
alias rest="reset"
alias rf="print -rl -- ./**/*(D.)"
alias srv="cd /Users/donaldmoore/src/dinglehopper/srv"
alias tsrv="cd /Users/donaldmoore/src/dinglehopper/srv && ./serve"
alias xdg-open="open"
alias xdg='cd "$XDG_CONFIG_HOME"'
alias z="cd $Z"

