#!/bin/zsh
# shellcheck disable=all

chpwd_git() {
  emulate -L zsh

  [[ -d ./.git ]] || return 0

  local top out
  top="$(git rev-parse --show-toplevel 2>/dev/null)" || return 0

  out="$(git remote -v 2>/dev/null | awk '{print $1 " " $2}' | sort -u)"

  if [[ -n "$out" ]]; then
      print -r -- "$out" | column -t | lolcat
      git status -s
  elif [[ "$PWD" == "$top" ]]; then
      print -Pr -- "%F{#FF2000}This is a git repository without a remote.%f [Frankenstein is angry] "
  fi
}
