#!/bin/zsh
# shellcheck disable=all

zmodload zsh/datetime # Use this with $EPOCHREALTIME

# chpwd hook: execute ./.automx in the current directory if present.
chpwd_breadcrumbs() {
#    emulate -L zsh
    local crumb="./.breadcrumb"
    if [[ ! -f "$crumb" ]]; then
	touch "./.breadcrumb"
    fi
    if [[ ! -z "$EPOCHREALTIME" ]]; then
	chmod 600 ./.breadcrumb
	echo "$EPOCHREALTIME" > ./.breadcrumb
    else
	$(date +%s) > ./.breadcrumb
    fi

}
